
services:
  # ----------------------------------------------------
  # 1. API (NestJS)
  # ----------------------------------------------------
  - type: web
    name: weather-api
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false     # Set this manually to your MongoDB Atlas URI
      - key: FRONTEND_URL
        value: https://weather-frontend-p7am.onrender.com
      - key: RABBIT_URL
        sync: false # Set manually (e.g. CloudAMQP)
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: ADMIN_CITY
        value: SÃ£o Paulo
      - key: COLLECTOR_URL
        value: https://weather-collector-fdhz.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        value: noreply@weather-dashboard.com

  # ----------------------------------------------------
  # 2. Frontend (React/Vite)
  # ----------------------------------------------------
  - type: web
    name: weather-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && node server.js
    envVars:
      - key: VITE_API_URL
        value: https://weather-api-p6v8.onrender.com/api

  # ----------------------------------------------------
  # 3. Collector (Python)
  # ----------------------------------------------------
  - type: web
    name: weather-collector
    env: docker
    dockerContext: ./Collector
    dockerfilePath: ./Collector/Dockerfile
    plan: free
    envVars:
      - key: RABBIT_URL
        sync: false # Set manually

  # ----------------------------------------------------
  # 4. IA Service (Python)
  # ----------------------------------------------------
  - type: web
    name: weather-ia-service
    env: docker
    dockerContext: ./IA-Service
    dockerfilePath: ./IA-Service/Dockerfile
    plan: free
    envVars:
      - key: RABBIT_URL
        sync: false # Set manually
      - key: GROQ_API_KEY
        sync: false

  # ----------------------------------------------------
  # 5. Worker GO
  # ----------------------------------------------------
  - type: web
    name: weather-worker-go
    env: docker
    dockerContext: ./Worker-GO
    dockerfilePath: ./Worker-GO/Dockerfile
    plan: free
    envVars:
      - key: RABBIT_URL
        sync: false # Set manually
      - key: NESTJS_URL
        value: https://weather-api-p6v8.onrender.com/api/weather/logs
